# Generated by Django 3.2 on 2022-11-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coleccion', models.CharField(max_length=100, verbose_name='Colección')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('tamano', models.CharField(max_length=8, verbose_name='Tamaño')),
                ('imagen_funda', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
    ]
