# Generated by Django 4.1.2 on 2022-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_funda_almohadon_funda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='almohadon',
            name='funda',
        ),
        migrations.DeleteModel(
            name='Funda',
        ),
    ]
